#!/bin/bash

Name=$1
if [ ! -f "${Name}" ]; then
    echo 'File does not exist'
    exit 1
fi
baseName=$(echo "${Name}" | awk -F'_' '{print $1}')
awk '/Step Temp PotEng/,/Loop time of /' "${Name}" | head -n -2 | awk '{printf("%s,%s,%s,%s,%s,%s,%s\n",$1,$2,$3,$4,$5,$6,$7)}' > "${baseName}_purethermo.data"
